name: Deploy Hello World via Helm

on:
  workflow_dispatch:
    push:
      branches: ["main"]
        
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: eu-central-1
      ENV: dev


    steps:

      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials/@v5.1.0
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Setup kubectl
        uses: azure/setup-kubectl@v4

      - name: Setup Helm
        uses: azure/setup-helm@v4.3.0

      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig \
            --region eu-central-1 \
            --name home-assignment-eks

      - name: Verify connection
        run: |
          kubectl get nodes

      - name: Deploy hello-world app
        run: make deploy-hello ENV=${{ env.ENV }}


